package:
  name: blobfuse2
  version: 2.4.2
  epoch: 0
  description: A virtual file system adapter for Azure Blob storage
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - fuse3-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 25d91613a14bc3847d4443188340cc7e4c65a43f
      repository: https://github.com/Azure/azure-storage-fuse
      tag: ${{package.name}}-${{package.version}}

  - uses: go/build
    with:
      output: blobfuse2
      packages: .

subpackages:
  - name: "${{package.name}}-health-monitor"
    description: "Health monitor for blobfuse2"
    pipeline:
      - uses: go/build
        with:
          output: bfusemon
          packages: ./tools/health-monitor
    test:
      pipeline:
        - runs: |
            # Check basic help and version
            bfusemon --help
            bfusemon -version

update:
  enabled: true
  github:
    identifier: Azure/azure-storage-fuse
    strip-prefix: blobfuse2-
    tag-filter: blobfuse2-2.4.

test:
  pipeline:
    - runs: |
        # Check basic help and version
        blobfuse2 --help | grep "Blobfuse2 is an open source project"
        blobfuse2 --version | grep ${{package.version}}
