package:
  name: clickhouse-operator
  version: "0.24.5"
  epoch: 0
  description: Altinity Kubernetes Operator for ClickHouse creates, configures and manages ClickHouse® clusters running on Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Altinity/clickhouse-operator
      tag: release-${{package.version}}
      expected-commit: 2a4b0f2fa3e8a325cbc5b4739d9f74dc4854a9c7

  - uses: go/build
    with:
      packages: ./cmd/operator
      ldflags: "-w -X github.com/altinity/clickhouse-operator/pkg/version.Version=v${{package.version}} -extldflags"
      output: clickhouse-operator

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binary in the location expected by clickhouse-operator"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf /usr/bin/clickhouse-operator ${{targets.contextdir}}/clickhouse-operator

update:
  enabled: true
  github:
    identifier: Altinity/clickhouse-operator
    strip-prefix: release-

test:
  # Despite using KWOK or specifying a kubeconfig (e.g. `clickhouse-operator -kubeconfig "/root/.kube/config"`),
  # we still encounter this error:
  # {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs:
  #  clickhouse-keeper.altinity.com/v1:
  #  Get \"https://127.0.0.1:32764/apis/clickhouse-keeper.altinity.com/v1\": dial tcp 127.0.0.1:32764:
  #  connect: connection refused"}
  pipeline:
    - uses: test/tw/ldd-check
    - name: Basic tests
      runs: |
        clickhouse-operator -version
        clickhouse-operator -help
