package:
  name: crossplane-provider-aws
  version: "1.23.0"
  epoch: 1
  description: Official AWS Provider for Crossplane by Upbound
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates
      - curl

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 71f83d818b966c5575ba005736453c2fd011bf21
      repository: https://github.com/crossplane-contrib/provider-upjet-aws
      tag: v${{package.version}}

  - runs: |
      curl -fsSL "https://cli.upbound.io" | sh
      mv up /usr/bin/
      up version

data:
  - name: packages
    items:
      # family: provider-family-aws
      cloudfront: provider-aws-cloudfront
      cloudwatchlogs: provider-aws-cloudwatchlogs
      dynamodb: provider-aws-dynamodb
      ec2: provider-aws-ec2
      eks: provider-aws-eks
      firehose: provider-aws-firehose
      iam: provider-aws-iam
      kms: provider-aws-kms
      lambda: provider-aws-lambda
      rds: provider-aws-rds
      s3: provider-aws-s3
      sns: provider-aws-sns
      sqs: provider-aws-sqs

subpackages:
  - name: crossplane-provider-aws-${{range.key}}
    range: packages
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/provider/${{range.key}}
          output: ${{range.value}}
          ldflags: |
            -X github.com/crossplane-contrib/provider-upjet-aws/internal/version.Version=v${{package.version}}
      - runs: |
          up xpkg xp-extract xpkg.upbound.io/upbound/${{range.value}}:v1.23.1
          mkdir -p "${{targets.subpkgdir}}"
          gunzip out.gz -c > "${{targets.subpkgdir}}"/package.yaml
    test:
      pipeline:
        - runs: ${{range.value}}

update:
  enabled: true
  github:
    identifier: crossplane-contrib/provider-upjet-aws
    strip-prefix: v
    use-tag: true
