# NOTE: When updating this package, verify the latest upstream package versions from:
# https://marketplace.upbound.io/providers
#
# Upbound only allows free tier to pull 'latest' versions, so ensure all provider
# versions in the 'data' section below are updated to match the latest available
# versions on the marketplace. "crane export xpkg.upbound.io/upbound/${{range.value}}:<update-to-latest> > package.tar"
package:
  name: crossplane-provider-aws
  version: "1.23.0"
  epoch: 1
  description: Official AWS Providers for Crossplane by Upbound
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates
      - crane
      - curl

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 71f83d818b966c5575ba005736453c2fd011bf21
      repository: https://github.com/crossplane-contrib/provider-upjet-aws
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0

data:
  - name: packages
    items:
      cloudfront: provider-aws-cloudfront
      cloudwatchlogs: provider-aws-cloudwatchlogs
      config: provider-family-aws # https://github.com/crossplane-contrib/provider-workflows/blob/main/.github/workflows/publish-provider-family.yml#L230
      dynamodb: provider-aws-dynamodb
      ec2: provider-aws-ec2
      eks: provider-aws-eks
      firehose: provider-aws-firehose
      iam: provider-aws-iam
      kms: provider-aws-kms
      lambda: provider-aws-lambda
      rds: provider-aws-rds
      s3: provider-aws-s3
      sns: provider-aws-sns
      sqs: provider-aws-sqs

subpackages:
  - name: crossplane-provider-aws-${{range.key}}
    range: packages
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/provider/${{range.key}}
          output: ${{range.value}}
          ldflags: |
            -X github.com/crossplane-contrib/provider-upjet-aws/internal/version.Version=v${{package.version}}
      - runs: |
          crane export xpkg.upbound.io/upbound/${{range.value}}:v1.23.1 > package.tar
          mkdir -p "${{targets.subpkgdir}}"
          tar -xf package.tar package.yaml > "${{targets.subpkgdir}}"/package.yaml
          rm package.tar
    test:
      environment:
        contents:
          packages:
            - openssl
      pipeline:
        - uses: test/kwok/cluster
        - runs: |
            mkdir -p /tls/server
            openssl req -x509 -newkey rsa:2048 -keyout /tls/server/tls.key \
              -out /tls/server/tls.crt -days 1 -nodes -subj "/CN=test"
            chmod 600 /tls/server/tls.key
            chmod 644 /tls/server/tls.crt
            # Run the provider with timeout and expect connection error
            timeout 10 ${{range.value}} 2>&1 | grep -E "(logger.*provider-aws)" || echo "Provider started with expected behavior"

  - name: crossplane-provider-aws-${{range.key}}-compat
    range: packages
    description: Compatibility package for ${{range.key}} provider with standard provider binary name
    dependencies:
      runtime:
        - crossplane-provider-aws-${{range.key}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/${{range.value}} "${{targets.subpkgdir}}"/usr/local/bin/provider
    test:
      pipeline:
        - runs: |
            readlink -f "${{targets.subpkgdir}}"/usr/local/bin/provider | grep "${{range.value}}"

update:
  enabled: true
  github:
    identifier: crossplane-contrib/provider-upjet-aws
    strip-prefix: v
    use-tag: true
