package:
  name: fluent-plugin-multi-format-parser
  version: 1.1.0
  epoch: 0
  description: Multi format parser for Fluentd
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-fluentd

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-fluentd

vars:
  gem: fluent-plugin-multi-format-parser

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 5e65da57cef94a423ca8b23abd21020c98fc3e83
      repository: https://github.com/repeatedly/fluent-plugin-multi-format-parser
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: repeatedly/fluent-plugin-multi-format-parser
    strip-prefix: v
    use-tag: true