package:
  name: flux-operator
  version: "0.24.1"
  epoch: 1
  description: Flux Operator creates and manages Flux instances running in Kubernetes
  copyright:
    - license: AGPL-3.0-or-later

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 09d991b9168009d84a3ebef203a60d4af18ec3ab
      repository: https://github.com/controlplaneio-fluxcd/flux-operator.git
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/operator/main.go
      output: flux-operator
      ldflags: -X main.VERSION=${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/mcp/
      output: flux-operator-mcp
      ldflags: -X main.VERSION=${{package.version}}

subpackages:
  - name: ${{package.name}}-compat
    description: compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -sf /usr/bin/flux-operator ${{targets.contextdir}}/flux-operator
          ln -sf /usr/bin/flux-operator-mcp ${{targets.contextdir}}/flux-operator-mcp
    test:
      pipeline:
        - runs: |
            stat /flux-operator
            stat /flux-operator-mcp

update:
  enabled: true
  github:
    identifier: controlplaneio-fluxcd/flux-operator
    strip-prefix: v

test:
  environment:
    environment:
      RUNTIME_NAMESPACE: "default"
    contents:
      packages:
        - helm
        - curl
  pipeline:
    - runs: |
        /usr/bin/flux-operator --help 2>&1 | grep metrics-addr
        /usr/bin/flux-operator-mcp -v | grep "${{package.version}}"
    - uses: test/kwok/cluster
    - name: "Functional test for opertor"
      uses: test/daemon-check-output
      with:
        setup: |
          helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator --namespace flux-system --create-namespace
        start: |
          flux-operator --enable-leader-election=false
        timeout: 30
        expected_output: |
          Starting EventSource
          Starting workers
          Starting Controller
        post: |-
          curl -fsSL localhost:8080/metrics | grep -i "workqueue_work_duration_seconds_bucket"
    # - name: "Functional test for operator-mcp"
    #   uses: test/daemon-check-output
    #   with:
    #     setup: |
    #       helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp --namespace flux-system --create-namespace
    #     start: |
    #       flux-operator-mcp --enable-leader-election=false
    #     timeout: 30
    #     expected_output: |
    #       Starting EventSource
    #       Starting workers
    #       Starting Controller
    #     post: |-
    #       curl -fsSL localhost:8080/metrics | grep -i "workqueue_work_duration_seconds_bucket"
