# source is gitlab so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: gitlab-17.1
  version: 17.1.1
  epoch: 0
  description: GitLab is an open source end-to-end software development platform with built-in version control, issue tracking, code review, CI/CD, and more.
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d0ac56e0be2576f3101025fb4a977a5e2a88d3ab
      repository: https://gitlab.com/gitlab-org/gitlab.git
      tag: v${{package.version}}-ee

subpackages:
  - name: ${{package.name}}-workhorse
    pipeline:
      - uses: go/bump
        with:
          deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 golang.org/x/image@v0.18.0
          modroot: ./workhorse
      - uses: go/build
        with:
          modroot: ./workhorse
          packages: ./cmd/gitlab-workhorse
          output: workhorse
      - uses: strip

  - name: ${{package.name}}-resize-image
    pipeline:
      - uses: go/build
        with:
          modroot: ./workhorse
          packages: ./cmd/gitlab-resize-image
          output: resize-image
      - uses: strip

  - name: ${{package.name}}-zip-cat
    pipeline:
      - uses: go/build
        with:
          modroot: ./workhorse
          packages: ./cmd/gitlab-zip-cat
          output: zip-cat
      - uses: strip

  - name: ${{package.name}}-zip-metadata
    pipeline:
      - uses: go/build
        with:
          modroot: ./workhorse
          packages: ./cmd/gitlab-zip-metadata
          output: zip-metadata
      - uses: strip

update:
  manual: true
  enabled: true
  release-monitor:
    identifier: 373181

test:
  pipeline:
    - runs: |
        workhorse --version
