package:
  name: kubernetes-csi-external-resizer
  version: 1.12.0
  epoch: 0
  description: Sidecar container that watches Kubernetes PersistentVolumeClaims objects and triggers controller side expansion operation against a CSI endpoint
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-resizer
      tag: v${{package.version}}
      expected-commit: 57aecf4c0c80dbbafda533d2f13ec11321e97c53

  - uses: go/build
    with:
      packages: ./cmd/csi-resizer
      ldflags: "-s -w -X main.version=v${{package.version}} -extldflags '-static'"
      output: csi-resizer

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-resizer
    strip-prefix: v

test:
  pipeline:
    - runs: csi-resizer --version
