package:
  name: kubernetes-csi-external-attacher
  version: 4.7.0
  epoch: 0
  description: Sidecar container that watches Kubernetes VolumeAttachment objects and triggers ControllerPublish/Unpublish against a CSI endpoint
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-attacher
      tag: v${{package.version}}
      expected-commit: ac93ce17a8a602f9310085a86b88a72230231257

  - uses: go/build
    with:
      packages: ./cmd/csi-attacher
      ldflags: "-s -w -X main.version=v${{package.version}} -extldflags '-static'"
      output: csi-attacher

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-attacher
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - openssl
  pipeline:
    - uses: test/kwok/cluster
    - runs: |
        sleep 5
        mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        CA=$(kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority}')
        cp $CA /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

        kubectl create clusterrolebinding default --clusterrole=cluster-admin --serviceaccount=default:default
        kubectl create token default > /var/run/secrets/kubernetes.io/serviceaccount/token

        # Set environment variables for csi-attacher
        export KUBERNETES_SERVICE_HOST=127.0.0.1
        export KUBERNETES_SERVICE_PORT=32764

        # Start the csi-attacher
        csi-attacher --http-endpoint :8080 > csi-attacher.log 2>&1 &
        CSI_ATTACHER_PID=$!

        # Allow some time for csi-attacher to start
        sleep 5

        # Check for expected log output
        if grep -q 'Listening for connections' csi-attacher.log; then
          echo "Test passed: Found expected log output."
        else
          echo "Test failed: Did not find expected log output."
          echo "csi-attacher logs:"
          cat csi-attacher.log
          exit 1
        fi
