package:
  name: optipng
  version: 0.7.8
  epoch: 0
  description: optiPNG is a PNG optimizer that recompresses image files to a smaller size, without losing any information
  copyright:
    - license: Zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://sourceforge.net/projects/optipng/files/optipng-${{package.version}}.tar.gz
      expected-sha256: 25a3bd68481f21502ccaa0f4c13f84dcf6b20338e4c4e8c51f2cefbd8513398c

  # cannot use autoconf/configure, since ./configure doesn't recognise --host.
  - runs: |
      ./configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 2571

test:
  environment:
    contents:
      packages:
        - zlib
        - wget
        - busybox
        - imagemagick
  pipeline:
    - name: Verify OptiPNG Version
      runs: |
        version_output=$(optipng --version)
        if echo "$version_output" | grep -q "OptiPNG version 0.7.8"; then
          echo "Version check passed: OptiPNG 0.7.8"
        else
          echo "Version mismatch! Expected OptiPNG 0.7.8."
          exit 1
        fi
    - name: Test PNG Optimization
      runs: |
        wget -q https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg -O cat.jpg
        magick convert cat.jpg cat.png
        optipng cat.png
        [ -f cat.png ] || { echo "Optimized PNG file not found!"; exit 1; }
        echo "PNG optimization completed successfully."