# pgAdmin4 17.0 is intended to support PostgreSQL 17.
# https://github.com/pgadmin-org/pgadmin4/blob/28eb2c0b4bcb229763cb0e160953e15ef9921dd4/Dockerfile#L119-L155
package:
  name: pgadmin4-17
  version: "8.14"
  epoch: 0
  description: pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world.
  copyright:
    - license: PostgreSQL License
  dependencies:
    provides:
      - pgadmin4=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - gcc
      - glibc-locale-en
      - krb5-dev
      - libedit
      - libffi-dev
      - libjpeg-turbo
      - libldap
      - liblz4-1
      - libpq-17
      - libzstd1
      - nasm
      - nodejs
      - npm
      - postfix
      - postgresql-17-dev
      - python3-dev
      - rust
      - shadow
      - sudo
      - tzdata
      - yarn
      - optipng

var-transforms:
  - from: ${{package.version}}
    match: '\.'
    replace: "_"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9e58717321a434519875773707df78c020bcde40
      repository: https://github.com/pgadmin-org/pgadmin4
      tag: REL-${{vars.mangled-package-version}}

  - runs: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip setuptools
      pip install -r requirements.txt
      pip install --no-cache-dir sphinx
      pip install --no-cache-dir sphinxcontrib-youtube
      make docs
      make pip

      cd web
      export CPPFLAGS="-DPNG_ARM_NEON_OPT=0"
      npm install -g corepack
      corepack enable
      yarn set version berry
      yarn set version 3
      yarn install
      yarn run bundle

      mkdir -p ${{targets.destdir}}/usr/local/pgadmin4
      cp -R . ${{targets.destdir}}/usr/local/pgadmin4

update:
  version-separator: _
  enabled: true
  github:
    identifier: pgadmin-org/pgadmin4
    strip-prefix: REL-
    tag-filter: REL_8
    use-tag: true
