package:
  name: vendir
  version: 0.44.0
  epoch: 0
  description: Easy way to vendor portions of git repos, github releases, helm charts, docker image contents, etc. declaratively
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7326502a792ee9a9feea1a9bb1c883650fd55646
      repository: https://github.com/carvel-dev/vendir
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/oauth2@v0.27.0

  - uses: go/build
    with:
      packages: ./cmd/vendir
      output: vendir
      ldflags: -X carvel.dev/vendir/pkg/vendir/version.Version=v${{package.version}}

update:
  enabled: true
  github:
    identifier: carvel-dev/vendir
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: 'vendir version | grep ${{package.version}}

        vendir --version

        vendir --help

      '
    - name: Clone vendir repo and run tests
      runs: 'git clone --branch v${{package.version}} --depth 1 https://github.com/carvel-dev/vendir

        cd vendir

        # Original test commands would go here'
    - name: run sync
      runs: 'cd examples/inline

        vendir sync

      '
    - name: test help command
      runs: "# Test command help \nvendir --version\nvendir -h\nvendir sync -h\n"
    - name: test directory structure with inline content
      runs: "# Set up test directories\nmkdir -p test-vendir\ncd test-vendir\n\n# Create test vendir config with inline content\ncat <<EOF > vendir.yml\napiVersion: vendir.k14s.io/v1alpha1\nkind: Config\nminimumRequiredVersion: 0.12.0\ndirectories:\n- path: vendor\n  contents:\n  - path: inline-test\n    inline:\n      paths:\n        test.txt: \"Hello inline content\"\nEOF\n\n# Run vendir sync and verify results\nvendir sync\n[ -d vendor/inline-test ]\n[ -f vendor/inline-test/test.txt ]\ngrep -q \"Hello inline content\" vendor/inline-test/test.txt\n"
    - name: binary reliability check
      uses: test/tw/ldd-check
  environment:
    contents:
      packages:
        - git
